// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjyxgloxiiubmdhcnoqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqeXhnbG94aWl1Ym1kaGNub3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjU2NDEsImV4cCI6MjA3MTE0MTY0MX0.jrwY-sRG3YOt75UwBrRQAHS7cIL2ZuvzYO3XwA0IHRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    storageKey: 'supabase.auth.token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,  // ← THIS IS THE KEY FIX!
  }
});

// Debug logging
if (typeof window !== 'undefined') {
  supabase.auth.onAuthStateChange((event, session) => {
    console.log('🔄 Auth Event:', event);
    console.log('✅ Session exists:', !!session);
    if (session) {
      console.log('👤 User:', session.user.email);
    }
  });
}